// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package data

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (name) VALUES ($1)
RETURNING id, name
`

func (q *Queries) CreatePlayer(ctx context.Context, name string) (Player, error) {
	row := q.db.QueryRow(ctx, createPlayer, name)
	var i Player
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getHistory = `-- name: GetHistory :many
SELECT id, protagonist_id, opponent_id, protagonist_move, opponent_move, played_at
FROM interactions
ORDER BY played_at DESC
`

func (q *Queries) GetHistory(ctx context.Context) ([]Interaction, error) {
	rows, err := q.db.Query(ctx, getHistory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Interaction
	for rows.Next() {
		var i Interaction
		if err := rows.Scan(
			&i.ID,
			&i.ProtagonistID,
			&i.OpponentID,
			&i.ProtagonistMove,
			&i.OpponentMove,
			&i.PlayedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerByID = `-- name: GetPlayerByID :one
SELECT id, name FROM players WHERE id = $1
`

func (q *Queries) GetPlayerByID(ctx context.Context, id pgtype.UUID) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerByID, id)
	var i Player
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getPlayerByName = `-- name: GetPlayerByName :one
SELECT id, name FROM players WHERE name = $1
`

func (q *Queries) GetPlayerByName(ctx context.Context, name string) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerByName, name)
	var i Player
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listPlayers = `-- name: ListPlayers :many
SELECT id, name FROM players
ORDER BY name
`

func (q *Queries) ListPlayers(ctx context.Context) ([]Player, error) {
	rows, err := q.db.Query(ctx, listPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordInteraction = `-- name: RecordInteraction :exec
INSERT INTO interactions (protagonist_id, opponent_id, protagonist_move, opponent_move)
VALUES ($1, $2, $3, $4)
`

type RecordInteractionParams struct {
	ProtagonistID   pgtype.UUID
	OpponentID      pgtype.UUID
	ProtagonistMove string
	OpponentMove    string
}

func (q *Queries) RecordInteraction(ctx context.Context, arg RecordInteractionParams) error {
	_, err := q.db.Exec(ctx, recordInteraction,
		arg.ProtagonistID,
		arg.OpponentID,
		arg.ProtagonistMove,
		arg.OpponentMove,
	)
	return err
}
