// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package data

import (
	"context"
)

const getPlayerByName = `-- name: GetPlayerByName :one
SELECT id, name, wins FROM players WHERE name = $1
`

func (q *Queries) GetPlayerByName(ctx context.Context, name string) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerByName, name)
	var i Player
	err := row.Scan(&i.ID, &i.Name, &i.Wins)
	return i, err
}

const listPlayers = `-- name: ListPlayers :many
SELECT id, name, wins FROM players
ORDER BY name
`

func (q *Queries) ListPlayers(ctx context.Context) ([]Player, error) {
	rows, err := q.db.Query(ctx, listPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(&i.ID, &i.Name, &i.Wins); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPlayerWin = `-- name: UpsertPlayerWin :exec
INSERT INTO players (name, wins) VALUES ($1, 1)
ON CONFLICT (name) DO UPDATE SET wins = players.wins + 1
`

func (q *Queries) UpsertPlayerWin(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, upsertPlayerWin, name)
	return err
}
